fix: Re-submitting the memory handling
Signed-off-by: ebadiere <ebadiere@gmail.com>

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -34,7 +34,14 @@ jobs:
         run: npm install -g pnpm
 
       - name: Build Typescript and Run tests
-        run: npm run build-and-test
+        run: |
+          output=$(npm run build-and-test 2>&1)
+          echo "$output"
+          if echo "$output" | grep -q "JavaScript heap out of memory"; then
+            echo "Heap out of Memory error detected"
+            exit 1
+          fi
+        shell: bash    
 
       - name: Upload coverage report
         if: ${{ always() && !cancelled() }}
